### ISSUE TITLE
shellext.exe / strings issue

### ISSUE THREAD

**Issue by mr-tz** [dzzie/MAP#3]
When running strings on executable files, I get an error message like this: `Error loading imports getting file offset from rva? rva=73728 offset=0`.

![2018-02-02_17-23-15](https://user-images.githubusercontent.com/17606537/35728319-cc0fc868-083d-11e8-8dd1-12be4fac609e.png)

Tested on 64-bit Windows 7.

**Comment by dzzie** [comment]
roger will address this soon, have seen it a couple times myself, unchecking the strings option to show addresses might stop it for now

**Comment by dzzie** [comment]
I have disabled the error message for now, bug not really fixed but at least it wont annoy and only minimal effect for now. real fix is to add x64 support to the PE library which will take more time

**Comment by mr-tz** [comment]
Great, thanks for the quick fix.

**Comment by dzzie** [comment]
I upgraded the pe parsing lib to sppe3 which is now fully x64 capable. also added a new reference to vbUTypes.dll for x64 number support. Should all be x64 Safe now. Additionally added 

md5 -> external -> DllCharacteristics form to view/remove dep/aslr/force integrity flags

fresh installer: http://sandsprite.com/CodeStuff/map_setup.exe

**Comment by mr-tz** [comment]
Thank you, I tested with the new installer and don't encounter the error anymore. However, when analyzing executable files, checking the `Offsets` box and selecting `va`, I get the following error and the process terminates.

![2018-02-22_10-56-08](https://user-images.githubusercontent.com/17606537/36519613-14e48cd2-17bf-11e8-8a01-777f5cad2a18.png)

**Comment by dzzie** [comment]
ok that was a weird bug, Im pretty sure i tested on win7 and it was ok, testing now on win8 and it happened. for some reason disabling file system redirection before calling sppe3.LoadFile was causing the system to not be able to find the stddll utypes.dll. This happened even if I manually loaded utypes.dll into memory before doing disabling filesystem redir. pretty weird behavior. more over this does not effect when i use pe.loadfile in the md5 hash form...

so anyway for now I have removed the calls to disable file system redirection in the strings form...this causes a new subtle bug in that you can not currently run strings on files in the x64 system32 directory.
lesser of two evils at this point. I uploaded a new installer for now and will tackle the next bug sometime else.. :-\

**Comment by dzzie** [comment]
so the subtle bug of not being able to use right click strings on files in the x64 system directory is going to have to stay. its not worth fixing...spent way to many hours on it and tried everything I can think of..vbruntime related best i can figure. not worth making a mess of the code to support that one thing. All the macro problems should be good now though.

**Comment by mr-tz** [comment]
That works for me. Thank you very much!

**Comment by dzzie** [comment]
I was also able to fix the subtle bug of strings not working on files in x64 system32 directory. After trying everything (even complex things), I finally gave up and cheated.

```basic
If Is64BitProcessor() And InStr(1, fPath, Environ("windir") & "\System32", vbTextCompare) > 0 Then
        'file system redirection is stupid, pe.loadfile dll dependancies fail to load with redir off..tried everything..
        tmp = Environ("temp") & "\" & fso.FileNameFromPath(fPath)
        fs = DisableRedir()
        If fso.FileExists(tmp) Then fso.DeleteFile tmp
        FileCopy fPath, tmp
        RevertRedir
        fPath = tmp
    End If
```
